<fieldset class="col s12 center" >
<div class="row">
    <form class="col s12 center-align" id="cadastroForm" action="">
        <div class="row">
            <div class="input-field col s6">
                <input id="last_name" type="text" class="validate">
                <label for="last_name">Nome</label>
            </div>
            <div class="input-field col s6">
                <input id="last_name" type="text" class="validate">
                <label for="last_name">Sexo</label>
            </div>
        </div>
        <div class="row">
        <div class="input-field col s6">
            <input id="last_name" type="text" class="validate">
            <label for="last_name">Email</label>
        </div>
        <div class="input-field col s6">
            <input id="last_name" type="text" class="validate">
            <label for="last_name">Confirme seu Email</label>
        </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <input id="password" type="password" class="validate">
                <label for="password">Senha</label>
            </div>
            <div class="input-field col s6">
                <input id="password" type="password" class="validate">
                <label for="password">Confirme sua senha</label>
            </div>
        </div>
        <div class="row">
            <div class="col s12 pull-right">
                <div class="col s4">
                    <a class="waves-effect waves-light btn grey"><i class="material-icons left">check</i>Limpar</a>
                 </div>
                <div class="col s4">
                    <a class="waves-effect waves-light btn red"><i class="material-icons left">cloud</i>Cancelar</a>
                </div>
                <div class="col s4">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Cadastrar
                        <i class="material-icons right">send</i>
                    </button>

                </div>
            </div>
        </div>
    </form>
</div>
</fieldset>