<?php echo $this->doctype(); ?>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Materialize'); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/materialize.min.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/asset/application/meuProjeto.css')
        ->prependStylesheet($this->basePath() . 'http://fonts.googleapis.com/icon?family=Material+Icons')
    ?>
</head>
<body>
<header>
    <nav class="top-nav teal lighten-2" >
        <div class="container">
            <div class="nav-wrapper">
        <a class="page-title"> Ortho Life</a>
            </div>
        </div>
    </nav>

</header>

<main class="">
    <aside >
        <ul id="nav-mobile" class="side-nav fixed">
            <li class="logo">
                <a id="logo-container" href="/" class="brand-logo"></a>
            </li>
            <li class="bold">
                <a href="/" class="waves-effect waves-teal">Indicar um paciente</a>
                <span class="new badge red"></span>
            </li>
            <li class="bold"><a href="#" class="waves-effect waves-teal">Menu 2</a></li>
            <li class="no-padding">
                <ul class="collapsible collapsible-accordion">
                    <li class="bold"><a class="collapsible-header waves-effect waves-teal">Menu 3</a>
                        <div class="collapsible-body">
                            <ul>
                                <li><a href="#">Sub Menu 1</a></li>
                                <li><a href="#">Sub Menu 2</a></li>
                                <li><a href="#">Sub Menu 3</a></li>
                                <li><a href="#">Sub Menu 4</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="bold"><a class="collapsible-header waves-effect waves-teal">Menu 4</a>
                        <div class="collapsible-body">
                            <ul>
                                <li><a href="#">Sub Menu 1</a></li>
                                <li><a href="#">Sub Menu 2</a></li>
                                <li><a href="#">Sub Menu 3</a></li>
                                <li><a href="#">Sub Menu 4</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="bold"><a class="collapsible-header waves-effect waves-teal">Menu 5</a>
                        <div class="collapsible-body">
                            <ul>
                                <li><a href="#">Tabs</a></li>
                                <li><a href="#">Transitions</a></li>
                                <li><a href="#">Waves</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </li>

        </ul>

    </aside>
    <section id="container-conteudo">
        <div class="row">
            <div class="col s12 contentView">
                <?php echo $this->content ?>
            </div>
        </div>
    </section>
</main>
 <!-- Scripts -->
 <?php echo $this->headScript()
     ->prependFile($this->basePath() . '/js/materialize.min.js')
     ->prependFile($this->basePath() . 'https://code.jquery.com/jquery-2.1.1.min.js')
     ->prependFile($this->basePath() . '/js/jquery.min.js')
     ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
     ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
 <script>
     $(function () {
         $(".button-collapse").sideNav();
     });
 </script>
</body>
</html>
